version: '3.9'

services:
    api:
        container_name: gdp-back-api
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        volumes:
            - ./:/app
        ports:
            - 3003:3003
        depends_on:
            - mongodb
            - redis
        networks:
            networkgdp:
                aliases:
                    - api

    mongodb:
        container_name: gdp-back-mongodb
        image: mongo
        restart: always
        ports:
            - 27030:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
        volumes:
            - ./data/mongodb-data:/data/db
        networks:
            networkgdp:
                aliases:
                    - mongodb

    redis:
        container_name: gdp-back-redis
        image: redis

        ports:
            - 6399:6379
        # environment:
        #     REDIS_PASSWORD: ${REDIS_PASSWORD}
        networks:
            networkgdp:
                aliases:
                    - redis

networks:
    networkgdp:
        name: networkgdp
        driver: bridge

volumes:
    mongodb-data:
