version: '3.9'

services:
    mongodb:
        container_name: gdp-back-mongodb
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
        volumes:
            - mongodb-data:/data/db
        networks:
            - networkgdp

    redis:
        container_name: gdp-back-redis
        image: redis
        restart: unless-stopped
        command: redis-server --appendonly yes # Enables AOF persistence
        volumes:
            - redis-data:/data # Persist Redis data
        networks:
            - networkgdp

    api:
        container_name: gdp-back-api
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        volumes:
            - ./:/app
            - /app/node_modules # Prevent overwrite of node_modules directory
        ports:
            - 3003:3003
        depends_on:
            - mongodb
            - redis
        networks:
            - networkgdp

networks:
    networkgdp:
        driver: bridge

volumes:
    mongodb-data:
    redis-data: # Added Redis data volume
