version: '3.7'
services:
    mongo:
        image: mongo
        container_name: mongodb_6_gdp

        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 27021:27017
        volumes:
            - ../db/mongodb_6_gdp/data/db:/data/db
        restart: unless-stopped
