name: Wakatime Readme Stats

on:
    schedule:
        - cron: '0 0 * * *'
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Debug Environment
              run: |
                  echo "Repository: ${{ github.repository }}"
                  echo "Actor: ${{ github.actor }}"
                  echo "Ref: ${{ github.ref }}"

            - name: Check secrets
              run: |
                  if [ -n "${{ secrets.WAKATIME_API_KEY }}" ]; then echo "WAKATIME_API_KEY is set"; else echo "WAKATIME_API_KEY is not set"; fi
                  if [ -n "${{ secrets.GH_TOKEN }}" ]; then echo "GH_TOKEN is set"; else echo "GH_TOKEN is not set"; fi

            - name: Update Readme
              uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_OS: 'True'
                  SHOW_PROJECTS: 'True'
                  SHOW_EDITORS: 'True'
                  SHOW_TIMEZONE: 'True'
                  SHOW_COMMIT: 'True'
                  SHOW_LANGUAGE: 'True'
                  SHOW_LINES_OF_CODE: 'True'
                  SHOW_LANGUAGE_PER_REPO: 'True'
                  SHOW_LOC_CHART: 'True'
                  SHOW_DAYS_OF_WEEK: 'True'
                  SHOW_PROFILE_VIEWS: 'True'
                  SHOW_SHORT_INFO: 'True'
                  SHOW_UPDATED_DATE: 'True'
                  SHOW_TOTAL_CODE_TIME: 'True'
                  DEBUG_LOGGING: 'True'

            - name: Commit and push if changed
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Wakatime stats" && git push)
